import Head from "next/head";
import Image from "next/image";
import Page1 from "../components/Page1/page1";
import Courses from "../components/Courses/Courses";
import H1 from "../img/h-1.png";
import InfoList from "../components/InfoBox/InfoList";
import TechSliderList from "../components/Tech/TechSliderList";
import StudentCardList from "../components/Student/StudentCardList";
import Liner from "../img/liner1.png";
import A1 from "../img/a1.png";
import CourseList from "../components/CourseBox/CourseList";
import A2 from "../img/a2.png";
import D1 from "../img/d1.png";
import DisclosureC from "../components/Disclosure/Disclosure";

export default function Home(props) {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        {/* index section */}
        <div className="relative py-12 md:py-8 xl:py-0">
          <div className="container p-2 mx-auto min-h-[40vh] relative z-10  flex items-center flex-col md:flex-row">
            <div className=" w-full md:w-6/12 flex flex-col items-center z-50 md:items-center">
              <p className="text-3xl text-center capitalize font-bold mt-4 text-blue-400 md:text-4xl">
                Learn science from experts
              </p>
              <p className=" text-xl text-center mt-6">
                Start listening to yourself. Pay attention to reading. Start
                realizing your potential. Learn with us
              </p>

              <button className="rounded mt-6 font-bold text-xl block py-2 px-8  border border-[#24A776] text-[#24A776] transition-all hover:bg-[#24A776] hover:text-white">
                Start Now
              </button>
              <a
                href="#"
                className="mt-8 text-[#24A776] flex items-center text-xl"
              >
                <svg
                  className="mr-4"
                  fill="#24A776"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 24 24"
                >
                  <path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-3 17v-10l9 5.146-9 4.854z" />
                </svg>
                See it in action
              </a>
            </div>
            <div className="w-full mt-8 md:w-6/12 md:mt-0 relative z-50">
              <div className="w-full z-50">
                <Image src={H1} className="z-10" alt="standford course" />
              </div>
            </div>
          </div>

          <div className=" absolute z-0 left-0 right-0 bottom-0">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
              <path
                fill="#24a776"
                fillOpacity="1"
                d="M0,192L120,213.3C240,235,480,277,720,272C960,267,1200,213,1320,186.7L1440,160L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"
              ></path>
            </svg>
          </div>

          <div
            className="left-0 right-0 top-0 bottom-0  absolute -z-10 "
            style={{
              background: `url(${D1.src})`,
              backgroundSize: "cover",
              backgroundRepeat: "no-repeat",
            }}
          ></div>
        </div>

        {/* index section end */}

        {/* coures info */}
        <div className=" bg-[#24A776] py-14 relative">
          <div className="container relative p-4 mx-auto flex flex-col items-center z-10">
            <div className="w-full   text-center  md:mt-0">
              <div>
                <h1 className="text-white text-3xl capitalize font-bold ">
                  Get knwledge from teachers with 5 years experince with us
                </h1>
                <p className="text-white text-xl mt-6">
                  -- Every decision you make is important to us.
                </p>
                <p className="text-white text-xl ">
                  -- With us you will achieve your goal.
                </p>
                <p className="text-white text-xl">
                  -- Never stop learning. Move forward towards the goal.
                </p>
              </div>
            </div>
            <div className="w-full flex justify-center mt-8 ">
              <Image src={A1} alt="standford course" width={900} height={500} />
            </div>
          </div>
          <div className="absolute left-0 right-0 bottom-0 z-0">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
              <path
                fill="#fff"
                fillOpacity="1"
                d="M0,192L60,213.3C120,235,240,277,360,293.3C480,309,600,299,720,277.3C840,256,960,224,1080,202.7C1200,181,1320,171,1380,165.3L1440,160L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"
              ></path>
            </svg>
          </div>
        </div>
        {/* coures info end */}

        {/* info section */}
        <div className="-mt-6">
          <InfoList />
        </div>
        {/* info section end */}

        {/* course section  */}
        <div className="py-8">
          <p className="text-blue-400 text-center text-xl uppercase first-letter:text-2xl font-bold">
            Courses
          </p>
          <div className="text-center mt-4 mb-8">
            <h1 className="text-3xl font-bold text-gray-800 capitalize">
              we offer the following corses
            </h1>
            <p className="text-xl container mx-auto w-8/12 text-gray-600 mt-4">
              We will help you leverage our experince by breaking down the
              secret into small chunks that you can easily digest and apply to
              any digital strategy
            </p>
          </div>

          <CourseList />
        </div>
        {/* course section end */}

        {/* info section  */}
        <div className="bg-[#15c8ff] relative">
          <div className="container p-2 mx-auto relative z-50 flex flex-col items-center sm:flex-row py-12">
            <div className="w-full  sm:w-6/12">
              <Image
                className="shadow-md"
                src={A2}
                width={700}
                height={600}
                alt=""
              />
            </div>
            <div className="w-full my-6 text-center sm:w-6/12 sm:my-0 sm:text-left">
              <h1 className="text-2xl font-bold text-gray-800 md:text-4xl">
                Develop with us in every field
              </h1>
              <p className="text-xl mt-4 text-gray-600 md:text-2xl">
                -- Set your goals high.
              </p>
              <p className="text-xl  text-gray-600 md:text-2xl">
                {" "}
                -- Work on yourself and get results
              </p>
            </div>
          </div>

          <div className="absolute left-0 right-0 z-0 bottom-0">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
              <path
                fill="#fff"
                fillOpacity="1"
                d="M0,256L120,245.3C240,235,480,213,720,208C960,203,1200,213,1320,218.7L1440,224L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"
              ></path>
            </svg>
          </div>
          <div className="absolute left-0 right-0 z-0 top-0">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
              <path
                fill="#fff"
                fillOpacity="1"
                d="M0,96L120,101.3C240,107,480,117,720,112C960,107,1200,85,1320,74.7L1440,64L1440,0L1320,0C1200,0,960,0,720,0C480,0,240,0,120,0L0,0Z"
              ></path>
            </svg>
          </div>
        </div>
        {/* info section end */}

        {/* teacher section */}
        <div
          className="py-12"
          style={{
            backgroundImage:
              "linear-gradient(143deg, rgba(36,167,118,1) 2%, rgba(0,153,255,1) 48%, rgba(32,166,132,1) 87%)",
          }}
        >
          <div className="container mx-auto pt-8">
            <h1 className="text-3xl text-center border-b-2 p-4 md:text-4xl font-bold text-white">
              Teacher Team
            </h1>
          </div>
          <TechSliderList />
        </div>
        {/* teacher section end */}
        <section className="py-12">
          <h3 className="text-blue-400 px-8 py-4 text-xl uppercase first-letter:text-2xl font-bold">
            FAQ
          </h3>
          {props.faq.map((q, i) => (
            <DisclosureC key={i} question={q.question} answer={q.answer} />
          ))}
        </section>
      </main>
    </div>
  );
}

Home.defaultProps = {
  faq: [
    {
      question: "What is your refund policy?",
      answer: ` If you&apos;re unhappy with your purchase for any reason, email
                us within 90 days and we&apos;ll refund you in full, no
                questions asked. lorem ipsum dolor sit amet consectetur
                adipisicing elit. Voluptate, quisquam. lorem ipsum dolor sit
                amet consectetur adipisicing elit. Voluptate, quisquam.`,
    },
    {
      question: "Do you offer technical support?",
      answer: "No, we do not offer technical support.",
    },
  ],
};
